interface fibonacci {
    variant request {
        number(u32),
        numbers(tuple<u32, u32>),
    }

    variant response {
        number(u64),
        numbers(tuple<u64, u32>),
    }
}

world fibonacci-template-dot-os-v0 {
    import fibonacci;
    include process-v1;
}
