interface {package_name_kebab} {
    variant request {
        number(u32),
        numbers(tuple<u32, u32>),
    }

    variant response {
        number(u64),
        numbers(tuple<u64, u32>),
    }
}

world {package_name_kebab}-{publisher_dotted_kebab}-v0 {
    import {package_name_kebab};
    include process-v0;
}
